In [ ]:
import pandas as pd

#data = pd.read_csv("fake-news-data.csv")
data = ''

print(data.head())
print(data.info())

                                               title  \
0  HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...
1   Elijah Cummings Called Trump Out To His Face ...
2   Hillary Clinton Says Half Her Cabinet Will Be...
3  Russian bombing of U.S.-backed forces being di...
4  Britain says window to restore Northern Irelan...

                                                text                 date  \
0  There are two small problems with your analogy...         Dec 30, 2015
1  Buried in Trump s bonkers interview with New Y...        April 6, 2017
2  Women make up over 50 percent of this country,...       April 26, 2016
3  WASHINGTON (Reuters) - U.S. Defense Secretary ...  September 18, 2017
4  BELFAST (Reuters) - Northern Ireland s politic...   September 4, 2017

  fake_or_factual
0       Fake News
1       Fake News
2       Fake News
3    Factual News
4    Factual News
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            198 non-null    object
 1   text             198 non-null    object
 2   date             198 non-null    object
 3   fake_or_factual  198 non-null    object
dtypes: object(4)
memory usage: 6.3+ KB
None

In [3]:
data.columns

Index(['title', 'text', 'date', 'fake_or_factual'], dtype='object')

In [4]:
data.shape

(198, 4)

In [5]:
data['fake_or_factual'].value_counts()

fake_or_factual
Factual News    100
Fake News        98
Name: count, dtype: int64

In [6]:
data['title']

0      HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...
1       Elijah Cummings Called Trump Out To His Face ...
2       Hillary Clinton Says Half Her Cabinet Will Be...
3      Russian bombing of U.S.-backed forces being di...
4      Britain says window to restore Northern Irelan...
                             ...
193    AND SO IT BEGINS…INSPIRED BY GAY MARRIAGE RULI...
194     ‘Stand Your Ground’: FL Man Shoots At Teens P...
195     The Los Angeles Times Endorses Hillary Clinto...
196    FBI chief sought more funds for Russia probe d...
197    UNBELIEVABLE! Students Succeed In Removing US ...
Name: title, Length: 198, dtype: object

In [7]:
data['text']

0      There are two small problems with your analogy...
1      Buried in Trump s bonkers interview with New Y...
2      Women make up over 50 percent of this country,...
3      WASHINGTON (Reuters) - U.S. Defense Secretary ...
4      BELFAST (Reuters) - Northern Ireland s politic...
                             ...
193    Well, that didn t take long. Look for the firs...
194    Florida s toxic and dangerous  stand your grou...
195    As Politico reports an almost neck-and-neck ra...
196    WASHINGTON (Reuters) - Former FBI Director Jam...
197    This is not some small obscure community colle...
Name: text, Length: 198, dtype: object

In [8]:
data[data['fake_or_factual'] == "Fake News"]

,title,text,date,fake_or_factual
0,HOLLYWEIRD LIB SUSAN SARANDON Compares Muslim ...,There are two small problems with your analogy...,"Dec 30, 2015",Fake News
1,Elijah Cummings Called Trump Out To His Face ...,Buried in Trump s bonkers interview with New Y...,"April 6, 2017",Fake News
2,Hillary Clinton Says Half Her Cabinet Will Be...,"Women make up over 50 percent of this country,...","April 26, 2016",Fake News
5,Maxine Waters Makes Teens Chant ‘Impeach 45′ a...,Shame on Teen Vogue! Maxine Waters was a guest...,"Dec 10, 2017",Fake News
6,Jay Carney Let It Slip That He Knows Who Obam...,Former White House Press Secretary in the Obam...,"February 10, 2016",Fake News
...,...,...,...,...
191,Terrorist Jon Ritzheimer Uses Sobbing Daughte...,"Jon Ritzheimer, infamous hater of Muslims and ...","January 26, 2016",Fake News
193,AND SO IT BEGINS…INSPIRED BY GAY MARRIAGE RULI...,"Well, that didn t take long. Look for the firs...","Jul 2, 2015",Fake News
194,‘Stand Your Ground’: FL Man Shoots At Teens P...,Florida s toxic and dangerous stand your grou...,"July 17, 2016",Fake News
195,The Los Angeles Times Endorses Hillary Clinto...,As Politico reports an almost neck-and-neck ra...,"May 30, 2016",Fake News
197,UNBELIEVABLE! Students Succeed In Removing US ...,This is not some small obscure community colle...,"Oct 28, 2015",Fake News

In [9]:
data[data['fake_or_factual'] == "Factual News"]

,title,text,date,fake_or_factual
3,Russian bombing of U.S.-backed forces being di...,WASHINGTON (Reuters) - U.S. Defense Secretary ...,"September 18, 2017",Factual News
4,Britain says window to restore Northern Irelan...,BELFAST (Reuters) - Northern Ireland s politic...,"September 4, 2017",Factual News
7,"Trump threat fires up U.S. climate activists, ...",(Reuters) - Seattle financial worker Harrison ...,"November 11, 2016",Factual News
9,China labels Trump call 'petty action' by Taiw...,BEIJING (Reuters) - U.S. President-elect Donal...,"December 3, 2016",Factual News
11,Kerry says can't comment on content of Clinton...,QUEBEC CITY (Reuters) - U.S. Secretary of Stat...,"January 29, 2016",Factual News
...,...,...,...,...
184,White House not aware of other nations plannin...,WASHINGTON (Reuters) - The White House said on...,"December 7, 2017",Factual News
185,Four killed as militants attack airport securi...,SRINAGAR (Reuters) - Indian police on Tuesday ...,"October 3, 2017",Factual News
188,Chinese aircraft drill again in Western Pacific,BEIJING (Reuters) - Chinese military aircraft ...,"December 21, 2017",Factual News
192,"France close to Qatar military, transport cont...",PARIS (Reuters) - France is close to finalizin...,"December 4, 2017",Factual News
196,FBI chief sought more funds for Russia probe d...,WASHINGTON (Reuters) - Former FBI Director Jam...,"May 10, 2017",Factual News

In [10]:
numbers = [10, 20, 30, 40]

for number in numbers:
    print(number)

10
20
30
40

In [11]:
numbers = [10, 20, 30, 40]

for number in numbers:
    if number > 20:
        print(number)

30
40

In [12]:
numbers = [10, 20, 30, 40]

result = [number * 2 for number in numbers]

print(result)

[20, 40, 60, 80]

In [ ]:
text = "Donald Trump visited New York yesterday."

['Donald', 'Trump', 'visited', 'New', 'York', 'yesterday.']

In [14]:
text.lower()

'donald trump visited new york yesterday.'

In [15]:
text.split()

['Donald', 'Trump', 'visited', 'New', 'York', 'yesterday.']

In [16]:
import re

re.sub(r"[^\w\s]", "", text)

'Donald Trump visited New York yesterday'

In [ ]:
data = pd.DataFrame({
    "text": [
        "I love this movie",
        "This movie is terrible",
        "Python is interesting",
        "Python is difficult"
    ],
    "label": [
        "positive",
        "negative",
        "positive",
        "negative"
    ]
})

In [ ]:
data.head()

: